### ISSUE TITLE
活动图名字显示甲乙丙

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-map-hp#4]

**Comment by Ayaphis** [comment]
乙丙难度进图如果是最后一格血做出“进入斩杀”的提示

**Comment by dkwingsmt** [comment]
进入斩杀的提示是好，也有很多人提过，但是你如何判断？如果是普通血条图的话得知道boss血量，这个实在不行就服务器收集，但是现在加了运输图，每次减绿条量跟桶有关……

**Comment by Ayaphis** [comment]
那就低于100提示吧

**Comment by alvin-777** [comment]
另外削甲程度不知道api给没给出来，如果也能显示就好了

**Comment by dkwingsmt** [comment]
感觉应该没有……应该只是在服务器端的敌方配置……

**Comment by yukixz** [comment]
hmm...
我只是说在 `[Event] 32-4 blablabla` 后面加个`丙`字而已=。=
你们想太多了吧

**Comment by yukixz** [comment]
你没有实现啊！
